apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: disney
  name: disney
spec:
  replicas: 1  # Scale up for availability
  selector:
    matchLabels:
      app: disney
  template:
    metadata:
      labels:
        app: disney
    spec:
      containers:
      - name: disney-container
        image: abhaypande/disney-hotstar:6
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: disney-hotstar
spec:
  selector:
    app: disney
  ports:
  - nodePort: 30000
    port: 3000
    targetPort: 3000
  type: NodePort  # Consider LoadBalancer if using on cloud

